### ISSUE TITLE
NEC, NOS terminology concept (unknown; other) (Hackathon)

### ISSUE THREAD

**Issue by vojtechhuser** [CBIIT/FHH#10]
The current web app is using not valid SnomedCT codes for other disease.

SNOMED philosophy is to reject such codes. 
These can be replaced with high level parent concepts.

> {"name":"Unknown Kidney Disease","abbr":"UKD","code":"UNKIDDIS","system":"SNOMED_CT"}
> {"name":"Unknown Lung Disease","abbr":"ULD","code":"UNLUNDIS","system":"SNOMED_CT"}
> {"name":"Unknown Psychological Disorder","abbr":"UPD","code":"UNPSYDIS","system":"SNOMED_CT"}

**Comment by vojtechhuser** [comment]
For "other kidney disease" it would be better to simply use "kidney disease"

http://browser.ihtsdotools.org/?perspective=full&conceptId1=90708001&edition=en-edition&release=v20160731&server=http://browser.ihtsdotools.org/api/snomed&langRefset=900000000000509007

**Comment by bremonline** [comment]
Cleaning up old issues.  There was a committee that recommended the diseases, names and codes.  We can revist in the future.
