### ISSUE TITLE
mother code (vs. parent (female)  (Hackathon)

### ISSUE THREAD

**Issue by vojtechhuser** [CBIIT/FHH#12]
The current xml export is exporting mother as female parent

see below code=PAR  (and gender female (as snomed code))

a better way would be to specify hl7 family member value.

![image](https://cloud.githubusercontent.com/assets/7526119/21865177/01c59d7c-d813-11e6-9c81-951e12e3b9c0.png)

**Comment by bremonline** [comment]
Cleaning up old comments.  Will revisit with an update to the format to use new FHIR standards is coming
