### ISSUE TITLE
SNOMED CT codes (IP issue) (Hackathon)

### ISSUE THREAD

**Issue by vojtechhuser** [CBIIT/FHH#13]
diseases.js  object exposes a lot of SnomedCT codes

Proper implementation would allow any condition to be used.
This would require whole SNOMED CT terminology.

This is subject to a license and should be used, but not so easily obtainable (in developer console - for example)

**Comment by bremonline** [comment]
Cleaning up old issues: Yeah, there are way too many diseases in a terminology like SNOMED to use.  The current list was designed by a committee, but can be revisited in the future.
