### ISSUE TITLE
what is use of keys.js

### ISSUE THREAD

**Issue by wistubbs** [CBIIT/FHH#2]
Great program but one of my issues is wanting to get it to run with nginx. Under nginx there are a lot of complaints about missing /js/keys.js . Interestingly using apache, it doesn't complain about keys.js .
But in fact there is not a /js/keys.js in the distribution. 
For example fhh.html asks for "../js/keys.js" but as I said it is not there. 
The problem I was having under nginx is it not being able to load saved data.

**Comment by bremonline** [comment]
Just updating old tickets: keys.js is old code required for HealthVault integration, file was never checked in as it had the encrypted key.  No longer needed.
