### ISSUE TITLE
How to add/modify diseases?

### ISSUE THREAD

**Issue by wistubbs** [CBIIT/FHH#3]
It would be great if there was info about modifying diseases in the program. 
I note that the disease list is coded in javascript. But there are also files that relate to diseases in
locales:
diseases-dev.json
diseases-en.json
diseases-en-US.json
diseases-es.json
diseases-it.json
diseases-pt.json
master:
diseases.json
So it would behoove someone to know how this system actually works in order to modify the 
diseases. Any chance of any docs about this?
 and data.

**Comment by bremonline** [comment]
Closing out old tickets: the diseases files are for translation.  If a language is detected, then it uses the appropriate Locale.  I beleive language locale was disabled years ago.
