### ISSUE TITLE
Allow enter just Year of Birth enywhere where day of birth is required (Hackathon)

### ISSUE THREAD

**Issue by vojtechhuser** [CBIIT/FHH#7]
For father of main subject, allow only enter year of birth (current website requires exact date of birth)

![image](https://cloud.githubusercontent.com/assets/7526119/21782671/3d3c1152-d682-11e6-9086-c39196ea316a.png)

**Comment by bobnih** [comment]
Date of birth is a dropdown for relatives, allowing to choose “age” or “estimated age” instead of exact dob. – Bob
